# Generated by Django 5.2.8 on 2026-01-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('concluído', 'Concluído'), ('pendente', 'Pendente')], default='agendado', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='relatocaso',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='relatocaso',
            name='ja_exibido',
        ),
        migrations.AddField(
            model_name='relatocaso',
            name='fonte',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='relatocaso',
            name='titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
