# Generated by Django 5.2.8 on 2026-03-10 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitulo', models.CharField(max_length=300)),
                ('texto', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('exibido_em', models.DateField(blank=True, null=True)),
                ('fonte', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissional', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('horario', models.TimeField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('pendente', 'Pendente'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profissional', 'date', 'horario'), name='uniq_appointment_profissional_date_horario')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('patient', 'Paciente'), ('psychologist', 'Psicologo')], default='patient', max_length=20)),
                ('bio', models.TextField(blank=True, null=True)),
                ('treatment_start_date', models.DateField(blank=True, help_text='Data de inicio do tratamento', null=True)),
                ('treatment_duration_days', models.IntegerField(blank=True, help_text='Duracao total do tratamento em dias', null=True)),
                ('activity_streak', models.IntegerField(default=0, help_text='Dias consecutivos de atividade')),
                ('today_activity_completed', models.BooleanField(default=False, help_text='Atividade do dia concluida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('treatment_duration_days__isnull', True), ('treatment_duration_days__gt', 0), _connector='OR'), name='userprofile_treatment_duration_positive_or_null')],
            },
        ),
    ]
