# Generated by Django 5.2.8 on 2026-03-10 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissional', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('horario', models.TimeField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('pendente', 'Pendente'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='relatocaso',
            name='ja_exibido',
        ),
        migrations.AddField(
            model_name='relatocaso',
            name='exibido_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatocaso',
            name='fonte',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relatocaso',
            name='subtitulo',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activity_streak',
            field=models.IntegerField(default=0, help_text='Dias consecutivos de atividade'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='today_activity_completed',
            field=models.BooleanField(default=False, help_text='Atividade do dia concluida'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='treatment_duration_days',
            field=models.IntegerField(blank=True, help_text='Duracao total do tratamento em dias', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='treatment_start_date',
            field=models.DateField(blank=True, help_text='Data de inicio do tratamento', null=True),
        ),
        migrations.AlterField(
            model_name='relatocaso',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Paciente'), ('psychologist', 'Psicologo')], default='patient', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(condition=models.Q(('treatment_duration_days__isnull', True), ('treatment_duration_days__gt', 0), _connector='OR'), name='userprofile_treatment_duration_positive_or_null'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('profissional', 'date', 'horario'), name='uniq_appointment_profissional_date_horario'),
        ),
    ]
