# Generated by Django 5.2.8 on 2026-02-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('concluído', 'Concluído'), ('pendente', 'Pendente')], default='agendado', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='relatocaso',
            old_name='texto',
            new_name='conteudo',
        ),
        migrations.RemoveField(
            model_name='relatocaso',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='relatocaso',
            name='ja_exibido',
        ),
        migrations.AddField(
            model_name='relatocaso',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='treatment_duration_days',
            field=models.IntegerField(blank=True, help_text='Duração total do tratamento em dias', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='treatment_start_date',
            field=models.DateField(blank=True, help_text='Data de início do tratamento', null=True),
        ),
        migrations.AlterField(
            model_name='relatocaso',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
