# Generated by Django 5.2.8 on 2025-12-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_relatocaso_subtitulo"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatocaso",
            name="exibido_em",
            field=models.DateField(blank=True, null=True),
        ),
    ]
