# Generated by Django 5.2.8 on 2026-01-25 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_appointment_remove_relatocaso_ativo_and_more"),
        ("core", "0003_remove_relatocaso_ja_exibido_relatocaso_exibido_em"),
    ]

    operations = []
