# Generated by Django 6.0.3 on 2026-03-23 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofile_user_alter_userprofile_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='uniq_appointment_profissional_date_horario',
        ),
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='userprofile_treatment_duration_positive_or_null',
        ),
        migrations.RemoveField(
            model_name='relatocaso',
            name='exibido_em',
        ),
        migrations.AddField(
            model_name='appointment',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_minhas_consultas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='psicologo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='core_agenda_profissional', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('agendado', 'Agendado'), ('concluida', 'Concluída')], default='disponivel', max_length=20),
        ),
        migrations.AlterField(
            model_name='relatocaso',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activity_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='today_activity_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='treatment_duration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='treatment_start_date',
            field=models.DateField(blank=True, help_text='Data de início', null=True),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='profissional',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
    ]
