# Generated by Django 5.2.8 on 2026-02-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_horario_timefield_and_profile_duration_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='today_activity_completed',
            field=models.BooleanField(default=False, help_text='Atividade do dia concluida'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='treatment_duration_days',
            field=models.IntegerField(blank=True, help_text='Duracao total do tratamento em dias', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='treatment_start_date',
            field=models.DateField(blank=True, help_text='Data de inicio do tratamento', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Paciente'), ('psychologist', 'Psicologo')], default='patient', max_length=20),
        ),
    ]
